# Generated by Django 5.0.7 on 2024-07-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='prie',
            new_name='price',
        ),
    ]
